# application.properties
spring:
  application:
    name: draftlighting

# ST API settings
smartthings:
  url: "https://api.smartthings.com/v1/"
  pat: faketoken

# ESPN Sports Core settings
espn:
  url: ${ESPN_URI:https://sports.core.api.espn.com/v2/}